### ISSUE TITLE
Need more description for Summarize Detections, hours to exclude

### ISSUE THREAD

**Issue by namariD** [allison-stokoe/Marina#2]
Please include the following text in the pop-up window where the user gets to input the hours to start/end analysis:

The title should say "Enter the first/last partial hours of the deployment"

Then, there should be smaller text under the table that says:
startHour= the hour the unit was deployed, a partial hour (not to be analyzed and
will be removed), and endHour= hour the unit was recovered, a partial hour (not to be
analyzed and will be removed).

**Comment by astokoe1** [comment]
fixed on 3/11/2021
